"use client";

import Link from "next/link";
import { ArrowRight, Building2, Droplets, Hammer, Home, Palette, Phone, Ruler, ShieldCheck, Wrench } from "lucide-react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";

const services = [
  { title: "Planning, Conception & Execution", description: "From initial ideas to final completion, we coordinate the details that keep your project moving with clarity and purpose.", icon: Ruler, features: ["Project planning", "Design coordination", "Construction execution"], link: "/contact" },
  { title: "Kitchen & Bathroom Renovation", description: "Functional, considered renovations with durable materials, thoughtful layouts, and quality finishes.", icon: Home, features: ["Kitchen transformations", "Bathroom upgrades", "Finish selection"], link: "/services/interior-remodeling" },
  { title: "Basement Renovation", description: "Unlock the potential of your basement with a comfortable, useful extension of your home or property.", icon: Hammer, features: ["Basement finishing", "Layout improvements", "Interior upgrades"], link: "/services/interior-remodeling" },
  { title: "General Renovation", description: "Refresh a single room or improve an entire property with practical solutions built around your needs.", icon: Wrench, features: ["Property improvements", "Interior renovations", "Repair coordination"], link: "/services/interior-remodeling" },
  { title: "Extension Projects", description: "Create additional space that integrates naturally with your existing structure and supports how you live or work.", icon: Building2, features: ["Space planning", "Expansion projects", "Project coordination"], link: "/contact" },
  { title: "Interior Design Services", description: "Bring layouts, materials, finishes, and function together with design direction tailored to your project.", icon: Palette, features: ["Layout concepts", "Materials and finishes", "Design coordination"], link: "/services/interior-remodeling" },
  { title: "Emergency Calls 24/7", description: "When an urgent property issue occurs, responsive construction support helps you understand the next steps.", icon: ShieldCheck, features: ["Urgent response", "Damage assessment", "Repair coordination"], link: "/contact" },
  { title: "Water Damage Restoration", description: "We help assess affected areas and coordinate the construction and restoration work needed to restore your property.", icon: Droplets, features: ["Affected-area review", "Restoration planning", "Property repairs"], link: "/services/repairs" },
];

const projectTypes = [
  ["Commercial", "Practical construction and renovation solutions designed around business operations."],
  ["Industrial", "Durable, carefully planned improvements for operational environments and facilities."],
  ["Residential", "Thoughtful renovations and additions that improve comfort, function, and value."],
];

export default function Services() {
  return <main className="bg-[#f4f5f7] text-[#252525]">
    <section className="relative overflow-hidden bg-[#071a33] px-6 py-32 text-white lg:px-10 lg:py-40"><div className="absolute inset-0 bg-[url('/icestudios.png')] bg-cover bg-center opacity-20" /><div className="relative mx-auto max-w-7xl"><p className="mb-5 text-sm font-bold uppercase tracking-[0.22em] text-[#c9a23a]">Build with confidence</p><h1 className="max-w-4xl text-5xl font-semibold leading-tight sm:text-7xl">Construction solutions for the spaces that matter.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-200">BuildWell Construction provides planning, renovation, design, and project management for commercial, industrial, and residential clients across Toronto and Ontario.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Button asChild size="lg" className="rounded-none bg-[#c9a23a] text-[#071a33] hover:bg-[#dfbb57]"><Link href="/contact">Get a free quote <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><a href="tel:+14376881994" className="inline-flex items-center justify-center gap-2 border border-white/40 px-6 py-3 font-semibold hover:bg-white hover:text-[#071a33]"><Phone className="h-4 w-4" /> (437) 688-1994</a></div></div></section>

    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="mb-12 max-w-2xl"><p className="mb-3 text-sm font-bold uppercase tracking-[0.2em] text-[#c9a23a]">Our services</p><h2 className="text-4xl font-semibold leading-tight text-[#071a33] sm:text-5xl">From the first conversation to the final detail.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Every project has different requirements. Our services are designed to support the full journey, whether you are improving a home, expanding a property, or preparing a commercial or industrial space.</p></div><div className="grid gap-px bg-slate-300 sm:grid-cols-2 lg:grid-cols-4">{services.map(({ title, description, icon: Icon, features, link }, index) => <motion.article key={title} whileHover={{ y: -5 }} className="flex min-h-[390px] flex-col bg-white p-7"><div className="flex items-center justify-between"><Icon className="h-8 w-8 text-[#c9a23a]" /><span className="text-sm text-slate-400">0{index + 1}</span></div><h3 className="mt-14 text-xl font-semibold leading-tight text-[#071a33]">{title}</h3><p className="mt-4 leading-7 text-slate-600">{description}</p><ul className="mt-auto space-y-2 pt-7 text-sm text-slate-500">{features.map((feature) => <li key={feature} className="flex items-center gap-2"><span className="h-1.5 w-1.5 bg-[#c9a23a]" />{feature}</li>)}</ul><Link href={link} className="mt-6 inline-flex items-center font-semibold text-[#071a33] hover:text-[#c9a23a]">Discuss this service <ArrowRight className="ml-2 h-4 w-4" /></Link></motion.article>)}</div></section>

    <section className="bg-white px-6 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><p className="mb-3 text-sm font-bold uppercase tracking-[0.2em] text-[#c9a23a]">Project types</p><h2 className="text-4xl font-semibold text-[#071a33] sm:text-5xl">Built around your environment.</h2><div className="mt-12 grid gap-px bg-slate-300 md:grid-cols-3">{projectTypes.map(([title, text], index) => <div key={title} className="bg-[#f4f5f7] p-8"><span className="text-sm text-[#c9a23a]">0{index + 1}</span><h3 className="mt-12 text-2xl font-semibold text-[#071a33]">{title}</h3><p className="mt-4 leading-7 text-slate-600">{text}</p></div>)}</div></div></section>

    <section className="bg-[#c9a23a] px-6 py-16 text-[#071a33] lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 sm:flex-row sm:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.2em]">Have a project in mind?</p><h2 className="mt-3 text-3xl font-semibold sm:text-4xl">Let&apos;s build the right plan.</h2></div><Button asChild size="lg" className="rounded-none bg-[#071a33] text-white hover:bg-white hover:text-[#071a33]"><Link href="/contact">Request a consultation <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></section>
  </main>;
}
